from __future__ import annotations

"""Unified scientific metadata for every integrated baseline.

Canonical ID rule: ``<domain>_<algorithm>_<citation>_<access>``.
The numerical implementations keep their original native IDs internally, while
all public APIs, reports and filenames use the canonical IDs below.
"""

from copy import deepcopy

BASELINE_METADATA = {'dct_dm_qim_chen2001_blind': {'canonical_id': 'dct_dm_qim_chen2001_blind',
                               'native_id': 'dct_dm_qim_chen2001',
                               'domain': 'dct',
                               'algorithm': 'dm_qim',
                               'citation': 'Chen-Wornell 2001',
                               'display_name': 'Chen-Wornell 2001 | DCT DM QIM | Blind',
                               'blindness_tier': 'blind',
                               'engine': 'functional',
                               'fidelity_tier': 'paper_modulation_common_image_adapter',
                               'requires_original_host': False,
                               'common_4096_payload': True,
                               'primary_blind_eligible': True,
                               'disclosure': {'native_status': 'paper_exact_pseudorandom_binary_dither_modulation_declared_dct_adapter',
                                              'common_adapter_status': 'paper_modulation_common_image_adapter',
                                              'paper_reproduction_eligible': False,
                                              'native_formula_reproduction_eligible': True,
                                              'common_primary_eligible': True,
                                              'blindness_tier': 'blind',
                                              'verified_capacity': 'one bit per selected 8x8 DCT block',
                                              'verified': ['pseudorandom zero-bit dither uniform on [-Delta/2,Delta/2)',
                                                           'one-bit dither displaced by Delta/2 according to the paper '
                                                           'rule',
                                                           'nearest-dithered-quantizer embedding and detection'],
                                              'adapted': ['8x8 luminance-DCT host transform',
                                                          'one declared coefficient',
                                                          'common payload schedule'],
                                              'unresolved_core_stages': [],
                                              'eligibility_reason': 'Primary common-protocol modulation baseline; no '
                                                                    'complete multimedia-system reproduction is '
                                                                    'claimed.',
                                              'native_method_id': 'dct_dm_qim_chen2001',
                                              'common_adapter_method_id': 'dct_dm_qim_chen2001',
                                              'evidence_files': ['baselines/evidence/dct_dm_qim_chen2001.yaml'],
                                              'status': 'paper_modulation_common_image_adapter',
                                              'common_benchmark_primary_eligible': True,
                                              'unresolved': []}},
 'dct_stdm_qim_chen2001_blind': {'canonical_id': 'dct_stdm_qim_chen2001_blind',
                                 'native_id': 'dct_stdm_qim_chen2001',
                                 'domain': 'dct',
                                 'algorithm': 'stdm_qim',
                                 'citation': 'Chen-Wornell 2001',
                                 'display_name': 'Chen-Wornell 2001 | DCT STDM QIM | Blind',
                                 'blindness_tier': 'blind',
                                 'engine': 'functional',
                                 'fidelity_tier': 'paper_modulation_common_image_adapter',
                                 'requires_original_host': False,
                                 'common_4096_payload': True,
                                 'primary_blind_eligible': True,
                                 'disclosure': {'native_status': 'paper_exact_spread_transform_dither_modulation_declared_dct_adapter',
                                                'common_adapter_status': 'paper_modulation_common_image_adapter',
                                                'paper_reproduction_eligible': False,
                                                'native_formula_reproduction_eligible': True,
                                                'common_primary_eligible': True,
                                                'blindness_tier': 'blind',
                                                'verified_capacity': 'one bit per selected 8x8 DCT block',
                                                'verified': ['seeded unit-norm spread-transform projection',
                                                             'pseudorandom binary dither quantization of the '
                                                             'projection',
                                                             'quantization displacement spread back along the '
                                                             'projection vector',
                                                             'nearest-dithered-quantizer detector'],
                                                'adapted': ['32-dimensional medium-frequency 8x8 luminance-DCT vector',
                                                            'common block scheduler'],
                                                'unresolved_core_stages': [],
                                                'eligibility_reason': 'Primary common-protocol STDM realization with '
                                                                      'the transform adapter explicitly declared.',
                                                'native_method_id': 'dct_stdm_qim_chen2001',
                                                'common_adapter_method_id': 'dct_stdm_qim_chen2001',
                                                'evidence_files': ['baselines/evidence/dct_stdm_qim_chen2001.yaml'],
                                                'status': 'paper_modulation_common_image_adapter',
                                                'common_benchmark_primary_eligible': True,
                                                'unresolved': []}},
 'dct_iss_malvar2003_blind': {'canonical_id': 'dct_iss_malvar2003_blind',
                              'native_id': 'dct_iss_malvar2003',
                              'domain': 'dct',
                              'algorithm': 'iss',
                              'citation': 'Malvar-Florencio 2003',
                              'display_name': 'Malvar-Florencio 2003 | DCT ISS | Blind',
                              'blindness_tier': 'blind',
                              'engine': 'functional',
                              'fidelity_tier': 'paper_modulation_common_image_adapter',
                              'requires_original_host': False,
                              'common_4096_payload': True,
                              'primary_blind_eligible': True,
                              'disclosure': {'native_status': 'paper_section_VA_maximum_useful_iss_declared_dct_adapter',
                                             'common_adapter_status': 'paper_modulation_common_image_adapter',
                                             'paper_reproduction_eligible': False,
                                             'native_formula_reproduction_eligible': True,
                                             'common_primary_eligible': True,
                                             'blindness_tier': 'blind',
                                             'verified_capacity': 'one bit per selected 8x8 DCT block',
                                             'verified': ['Section V-A maximum-useful-distortion rule around the '
                                                          'linear ISS displacement',
                                                          'unchanged correlation-sign detector',
                                                          'seeded unit-norm bipolar spreading sequences'],
                                             'adapted': ['28-dimensional upper-mid/high-frequency 8x8 luminance-DCT '
                                                         'vector',
                                                         'fixed lambda=0.90 common-protocol operating point',
                                                         'common block scheduler'],
                                             'unresolved_core_stages': [],
                                             'eligibility_reason': 'Primary common-protocol limited-distortion ISS '
                                                                   'baseline; the paper deliberately leaves the image '
                                                                   'transform open, so the adapter is disclosed.',
                                             'native_method_id': 'dct_iss_malvar2003',
                                             'common_adapter_method_id': 'dct_iss_malvar2003',
                                             'evidence_files': ['baselines/evidence/dct_iss_malvar2003.yaml'],
                                             'status': 'paper_modulation_common_image_adapter',
                                             'common_benchmark_primary_eligible': True,
                                             'unresolved': []}},
 'dct_ca_qim_mao2024_semiblind': {'canonical_id': 'dct_ca_qim_mao2024_semiblind',
                                  'native_id': 'ca_qim_a2_mao2024',
                                  'domain': 'dct',
                                  'algorithm': 'ca_qim_a2',
                                  'citation': 'Mao 2024',
                                  'display_name': 'Mao 2024 | DCT CA QIM A2 | Semi-blind',
                                  'blindness_tier': 'semi_blind',
                                  'engine': 'functional',
                                  'fidelity_tier': 'paper_core_common_image_adapter',
                                  'requires_original_host': False,
                                  'common_4096_payload': True,
                                  'primary_blind_eligible': False,
                                  'disclosure': {'native_status': 'paper_native_grayscale_A2_rate_and_SER_tracks_semi_blind',
                                                 'common_adapter_status': 'paper_core_common_image_adapter',
                                                 'paper_reproduction_eligible': False,
                                                 'native_formula_reproduction_eligible': False,
                                                 'native_metric_schema_reproduction_eligible': True,
                                                 'common_primary_eligible': False,
                                                 'blindness_tier': 'semi_blind',
                                                 'verified_capacity': 'four bits per A2/4A2 carrier vector',
                                                 'verified': ['paper-native grayscale 8x8 DCT track',
                                                              'A2 self-nested rate sweep for Tables II-III and fixed '
                                                              'R=2 SER track',
                                                              'paper bit-zero probability 0.9 in the native track',
                                                              'maximum-weight canonical labeling',
                                                              'nearest-point CA-QIM embedding and nearest-coset '
                                                              'decoding',
                                                              'image-dependent canonical labeling retained as '
                                                              'semi-blind detector side information'],
                                                 'adapted': ['one declared DCT coefficient pair per selected block',
                                                             'seeded common carrier schedule',
                                                             "balanced common watermark instead of forcing the paper's "
                                                             '0.9 zero prior',
                                                             'native-capacity repetition with soft minimum-distance '
                                                             'combining for a fixed 4096-bit user payload'],
                                                 'unresolved_core_stages': [],
                                                 'eligibility_reason': 'Paper-native grayscale/metric track is '
                                                                       'separate from the optional common '
                                                                       'balanced-payload adapter.',
                                                 'native_method_id': 'ca_qim_a2_mao2024',
                                                 'common_adapter_method_id': 'ca_qim_a2_mao2024',
                                                 'evidence_files': ['baselines/evidence/ca_qim_a2_mao2024.yaml'],
                                                 'status': 'paper_core_common_image_adapter',
                                                 'common_benchmark_primary_eligible': False,
                                                 'unresolved': []}},
 'dct_spread_spectrum_cox1997_nonblind': {'canonical_id': 'dct_spread_spectrum_cox1997_nonblind',
                                          'native_id': 'dct_spread_spectrum_cox1997',
                                          'domain': 'dct',
                                          'algorithm': 'spread_spectrum',
                                          'citation': 'Cox 1997',
                                          'display_name': 'Cox 1997 | DCT SPREAD SPECTRUM | Non-blind',
                                          'blindness_tier': 'non_blind',
                                          'engine': 'functional',
                                          'fidelity_tier': 'paper_core_informed_binary_sign_adapter',
                                          'requires_original_host': False,
                                          'common_4096_payload': True,
                                          'primary_blind_eligible': False,
                                          'disclosure': {'native_status': 'paper_native_informed_whole_image_DCT_spread_spectrum',
                                                         'common_adapter_status': 'paper_core_informed_binary_sign_adapter',
                                                         'paper_reproduction_eligible': False,
                                                         'native_formula_reproduction_eligible': False,
                                                         'native_metric_schema_reproduction_eligible': True,
                                                         'common_primary_eligible': False,
                                                         'blindness_tier': 'non_blind',
                                                         'verified_capacity': 'native 1000-sample Gaussian watermark; '
                                                                              'common adapter supports one sign bit '
                                                                              'per selected AC coefficient',
                                                         'verified': ['i.i.d. Gaussian native watermark sequence',
                                                                      'largest-magnitude whole-image DCT coefficient '
                                                                      'selection excluding DC',
                                                                      "multiplicative insertion v_i' = v_i(1 + alpha "
                                                                      'x_i)',
                                                                      'original selected coefficients used by the '
                                                                      'informed detector',
                                                                      'paper similarity response '
                                                                      'dot(x,x_hat)/norm(x_hat)'],
                                                         'adapted': ['RGB common adapter watermarks luminance',
                                                                     'binary sign payload is supplementary to the '
                                                                     'native continuous watermark detector'],
                                                         'unresolved_core_stages': [],
                                                         'eligibility_reason': 'Paper-supported informed baseline; '
                                                                               'detector access to original selected '
                                                                               'coefficients is preserved and '
                                                                               'disclosed.',
                                                         'native_method_id': 'dct_spread_spectrum_cox1997',
                                                         'common_adapter_method_id': 'dct_spread_spectrum_cox1997',
                                                         'evidence_files': ['baselines/evidence/dct_spread_spectrum_cox1997.yaml'],
                                                         'status': 'paper_core_informed_binary_sign_adapter',
                                                         'common_benchmark_primary_eligible': False,
                                                         'unresolved': []}},
 'dct_dew_langelaar2001_blind': {'canonical_id': 'dct_dew_langelaar2001_blind',
                                 'native_id': 'dew_langelaar2001',
                                 'domain': 'dct',
                                 'algorithm': 'dew',
                                 'citation': 'Langelaar 2001',
                                 'display_name': 'Langelaar 2001 | DCT DEW | Blind',
                                 'blindness_tier': 'blind',
                                 'engine': 'functional',
                                 'fidelity_tier': 'paper_core_decoded_frame_DCT_adapter',
                                 'requires_original_host': False,
                                 'common_4096_payload': False,
                                 'primary_blind_eligible': False,
                                 'disclosure': {'native_status': 'paper_supported_keyed_region_differential_energy_watermarking',
                                                'common_adapter_status': 'paper_core_decoded_frame_DCT_adapter',
                                                'paper_reproduction_eligible': False,
                                                'native_formula_reproduction_eligible': False,
                                                'common_primary_eligible': False,
                                                'blindness_tier': 'blind',
                                                'verified_capacity': 'one bit per keyed even-sized DCT-block region; '
                                                                     'at least two blocks per bit',
                                                'verified': ['keyed permutation of 8x8 luminance-DCT blocks',
                                                             'two energy subregions per label bit',
                                                             'D=E_A-E_B sign detector',
                                                             'paper coefficient-zeroing mode'],
                                                'adapted': ['decoded RGB frames rather than direct JPEG/MPEG '
                                                            'coefficient parsing',
                                                            'minimum-energy-removal mode for PSNR-controlled common '
                                                            'streaming'],
                                                'unresolved_core_stages': [],
                                                'eligibility_reason': 'Paper-supported blind real-time DCT-energy '
                                                                      'baseline; compressed-domain parsing is not '
                                                                      'claimed.',
                                                'native_method_id': 'dew_langelaar2001',
                                                'common_adapter_method_id': 'dew_langelaar2001',
                                                'evidence_files': ['baselines/evidence/dew_langelaar2001.yaml'],
                                                'status': 'paper_core_decoded_frame_DCT_adapter',
                                                'common_benchmark_primary_eligible': False,
                                                'unresolved': []}},
 'dwt_entropy_kumar2021_nonblind': {'canonical_id': 'dwt_entropy_kumar2021_nonblind',
                                    'native_id': 'kumar2021',
                                    'domain': 'dwt',
                                    'algorithm': 'entropy_alpha_blending',
                                    'citation': 'Kumar-Singh 2021',
                                    'display_name': 'Kumar-Singh 2021 | DWT ENTROPY ALPHA BLENDING | Non-blind',
                                    'blindness_tier': 'non_blind',
                                    'engine': 'class',
                                    'fidelity_tier': 'paper_guided_adaptation',
                                    'requires_original_host': True,
                                    'common_4096_payload': True,
                                    'primary_blind_eligible': False,
                                    'disclosure': {'blindness_tier': 'non_blind',
                                                   'fidelity_tier': 'paper_guided_adaptation',
                                                   'requires_original_host': True,
                                                   'common_4096_payload': True,
                                                   'primary_blind_eligible': False,
                                                   'note': 'Extraction requires the original host and stored watermark '
                                                           'subbands.'}},
 'dwt_qr_fa_guo2017_keyassisted': {'canonical_id': 'dwt_qr_fa_guo2017_keyassisted',
                                   'native_id': 'guo2017_dwt_qr_fa',
                                   'domain': 'dwt',
                                   'algorithm': 'qr_firefly',
                                   'citation': 'Guo 2017',
                                   'display_name': 'Guo 2017 | DWT QR FIREFLY | Key-assisted blind',
                                   'blindness_tier': 'key_assisted_blind',
                                   'engine': 'class',
                                   'fidelity_tier': 'paper_guided_implementation',
                                   'requires_original_host': False,
                                   'common_4096_payload': True,
                                   'primary_blind_eligible': False,
                                   'disclosure': {'blindness_tier': 'key_assisted_blind',
                                                  'fidelity_tier': 'paper_guided_implementation',
                                                  'requires_original_host': False,
                                                  'common_4096_payload': True,
                                                  'primary_blind_eligible': False,
                                                  'note': 'Stores a cover-dependent full-image sorting permutation; '
                                                          'report key size.'}},
 'dwt_hessenberg_fwa_gaata2022_keyassisted': {'canonical_id': 'dwt_hessenberg_fwa_gaata2022_keyassisted',
                                              'native_id': 'gaata2022_dwt_hess_fwa',
                                              'domain': 'dwt',
                                              'algorithm': 'hessenberg_fireworks',
                                              'citation': 'Gaata 2022',
                                              'display_name': 'Gaata 2022 | DWT HESSENBERG FIREWORKS | Key-assisted '
                                                              'blind',
                                              'blindness_tier': 'key_assisted_blind',
                                              'engine': 'class',
                                              'fidelity_tier': 'major_algorithm_adaptation',
                                              'requires_original_host': False,
                                              'common_4096_payload': True,
                                              'primary_blind_eligible': False,
                                              'disclosure': {'blindness_tier': 'key_assisted_blind',
                                                             'fidelity_tier': 'major_algorithm_adaptation',
                                                             'requires_original_host': False,
                                                             'common_4096_payload': True,
                                                             'primary_blind_eligible': False,
                                                             'note': 'Common mode replaces the paper decimal rule with '
                                                                     'QIM.'}},
 'dwt_hessenberg_svd_paper2025_semiblind': {'canonical_id': 'dwt_hessenberg_svd_paper2025_semiblind',
                                            'native_id': 'dwt_hd_svd_2025',
                                            'domain': 'dwt',
                                            'algorithm': 'hessenberg_svd',
                                            'citation': 'DWT-HD-SVD 2025',
                                            'display_name': 'DWT-HD-SVD 2025 | DWT HESSENBERG SVD | Semi-blind',
                                            'blindness_tier': 'semi_blind',
                                            'engine': 'class',
                                            'fidelity_tier': 'paper_guided_adaptation',
                                            'requires_original_host': False,
                                            'common_4096_payload': True,
                                            'primary_blind_eligible': False,
                                            'disclosure': {'blindness_tier': 'semi_blind',
                                                           'fidelity_tier': 'paper_guided_adaptation',
                                                           'requires_original_host': False,
                                                           'common_4096_payload': True,
                                                           'primary_blind_eligible': False,
                                                           'note': 'Key stores original host singular-value '
                                                                   'information.'}},
 'hessenberg_nha2023_blind': {'canonical_id': 'hessenberg_nha2023_blind',
                              'native_id': 'hess_nha2023',
                              'domain': 'hessenberg',
                              'algorithm': 'quantization',
                              'citation': 'Nha 2023',
                              'display_name': 'Nha 2023 | HESSENBERG QUANTIZATION | Blind',
                              'blindness_tier': 'blind',
                              'engine': 'class',
                              'fidelity_tier': 'common_payload_adaptation',
                              'requires_original_host': False,
                              'common_4096_payload': True,
                              'primary_blind_eligible': True,
                              'disclosure': {'blindness_tier': 'blind',
                                             'fidelity_tier': 'common_payload_adaptation',
                                             'requires_original_host': False,
                                             'common_4096_payload': True,
                                             'primary_blind_eligible': True,
                                             'note': 'Compact blind key; original 32x32 payload is adapted to 64x64.'}},
 'dwt_svd_roy2018_semiblind': {'canonical_id': 'dwt_svd_roy2018_semiblind',
                               'native_id': 'roy2018_dwt_svd',
                               'domain': 'dwt',
                               'algorithm': 'svd',
                               'citation': 'Roy 2018',
                               'display_name': 'Roy 2018 | DWT SVD | Semi-blind',
                               'blindness_tier': 'semi_blind',
                               'engine': 'class',
                               'fidelity_tier': 'formula_aligned_adaptation',
                               'requires_original_host': False,
                               'common_4096_payload': True,
                               'primary_blind_eligible': False,
                               'disclosure': {'blindness_tier': 'semi_blind',
                                              'fidelity_tier': 'formula_aligned_adaptation',
                                              'requires_original_host': False,
                                              'common_4096_payload': True,
                                              'primary_blind_eligible': False,
                                              'note': 'Key stores original singular values and watermark SVD '
                                                      'factors.'}},
 'dwt_wht_svd_kumar2024_semiblind': {'canonical_id': 'dwt_wht_svd_kumar2024_semiblind',
                                     'native_id': 'dwt_wht_svd_2024',
                                     'domain': 'dwt_wht',
                                     'algorithm': 'svd',
                                     'citation': 'Kumar et al. 2024',
                                     'display_name': 'Kumar et al. 2024 | DWT_WHT SVD | Semi-blind',
                                     'blindness_tier': 'semi_blind',
                                     'engine': 'class',
                                     'fidelity_tier': 'paper_guided_implementation',
                                     'requires_original_host': False,
                                     'common_4096_payload': True,
                                     'primary_blind_eligible': False,
                                     'disclosure': {'blindness_tier': 'semi_blind',
                                                    'fidelity_tier': 'paper_guided_implementation',
                                                    'requires_original_host': False,
                                                    'common_4096_payload': True,
                                                    'primary_blind_eligible': False,
                                                    'note': 'Requires original principal-component side information.'}},
 'qwt_qsvd_zhang2022_blind': {'canonical_id': 'qwt_qsvd_zhang2022_blind',
                              'native_id': 'qwt_qsvd_zhang2022_blind',
                              'domain': 'qwt',
                              'algorithm': 'qsvd',
                              'citation': 'Zhang 2022',
                              'display_name': 'Zhang 2022 | QWT QSVD | Blind',
                              'blindness_tier': 'blind',
                              'engine': 'class',
                              'fidelity_tier': 'paper_core_common_payload_adapter',
                              'requires_original_host': False,
                              'common_4096_payload': True,
                              'primary_blind_eligible': True,
                              'disclosure': {'blindness_tier': 'blind',
                                             'fidelity_tier': 'paper_core_common_payload_adapter',
                                             'requires_original_host': False,
                                             'common_4096_payload': True,
                                             'primary_blind_eligible': True,
                                             'note': 'Blind adapter with a cover-independent seeded block '
                                                     'permutation.'}},
 'qwt_qsvd_zhang2022_semiblind': {'canonical_id': 'qwt_qsvd_zhang2022_semiblind',
                                  'native_id': 'qwt_qsvd_zhang2022_semiblind',
                                  'domain': 'qwt',
                                  'algorithm': 'qsvd',
                                  'citation': 'Zhang 2022',
                                  'display_name': 'Zhang 2022 | QWT QSVD | Semi-blind',
                                  'blindness_tier': 'semi_blind',
                                  'engine': 'class',
                                  'fidelity_tier': 'paper_core_common_payload_adapter',
                                  'requires_original_host': False,
                                  'common_4096_payload': True,
                                  'primary_blind_eligible': False,
                                  'disclosure': {'blindness_tier': 'semi_blind',
                                                 'fidelity_tier': 'paper_core_common_payload_adapter',
                                                 'requires_original_host': False,
                                                 'common_4096_payload': True,
                                                 'primary_blind_eligible': False,
                                                 'note': 'Stores one image-dependent block selector per payload bit.'}},
 'iwt_svd_qim_zhu2021_blind': {'canonical_id': 'iwt_svd_qim_zhu2021_blind',
                               'native_id': 'zhu2021_iwt_svd_adapted',
                               'domain': 'iwt',
                               'algorithm': 'svd_qim',
                               'citation': 'Zhu 2021',
                               'display_name': 'Zhu 2021 | IWT SVD QIM | Blind',
                               'blindness_tier': 'blind',
                               'engine': 'class',
                               'fidelity_tier': 'conceptual_iwt_svd_qim_adapter',
                               'requires_original_host': False,
                               'common_4096_payload': True,
                               'primary_blind_eligible': False,
                               'disclosure': {'blindness_tier': 'blind',
                                              'fidelity_tier': 'conceptual_iwt_svd_qim_adapter',
                                              'requires_original_host': False,
                                              'common_4096_payload': True,
                                              'primary_blind_eligible': False,
                                              'note': '64x64 Y-channel fixed-QIM adapter; not an exact Zhu 2021 '
                                                      'reproduction.'}}}

NATIVE_TO_CANONICAL = {row["native_id"]: canonical for canonical, row in BASELINE_METADATA.items()}

def baseline_metadata(canonical_id: str) -> dict:
    if canonical_id not in BASELINE_METADATA:
        raise KeyError(f"Unknown canonical baseline id: {canonical_id}")
    return deepcopy(BASELINE_METADATA[canonical_id])

__all__ = ["BASELINE_METADATA", "NATIVE_TO_CANONICAL", "baseline_metadata"]
